package com.widged.maoriDictionary.dictionary.provider
{
	import com.widged.maoriDictionary.word.vo.WordItem;

	public class DictionaryData
	{
		public function DictionaryData()
		{
		}
		
		public static function get wordList():Array 
		{
			var arr:Array;
			arr = [];
			arr.push( new WordItem( "A", "A ", "", "<p>vowel: ā is pronounced as <i>a</i> in “art” and “father”; <b>a = ā</b> perceptibly shortened. The sound of <i>a</i> in “man” is unknown in Maori.</p>"));
			arr.push( new WordItem( "Ā", "A.-i ", "i","<p>n. <b>1</b>. <i>Collar-bone</i>. Usually joined with <m>kaki</m>. <m>Te a o toku kaki.</m></p> <p><b>2</b>. <i>Perch</i> for snaring <m>kaka</m>, a particular form of <m>mutu-kaka</m>.</p>"));
			arr.push( new WordItem( "Ā", "A.-ii ", "ii","<p>v.t. <b>1</b>. <i>Drive, urge, compel</i>. <m>Ka aia haeretia e te hau nunui</m> (J. iii, 99). <m>Ka rumaki tonu te pane ki te hoe, i te ainga hoki a te wehi</m> (T. 144).</p> <p>Two nouns are derived from this verb: <m>āinga, ānga</m>, <i>driving force, thing driven</i>, etc. <m>I te wa e rere ai te kano o te perehia i te āinga a te hau ki te moana</m> (W. iii, 35). <m>Kitea he anga na te haku</m> (P.).</p> <p><b>2</b>. <i>Collect</i>. <m>Ka whakahaua e Whatiuaroa tana ope; kei te a i te rakau hei wahie.</m></p>"));
			arr.push( new WordItem( "Ā", "A.-iii ", "iii","<p>Plural of the definitive particle <m>tā</m>, indicating possession. = <m>nga … a</m>, <i>the … of</i>. It is used before the dual and plural personal pronouns, names of persons or places, local nouns, or before common nouns preceded by a definitive (F.L. § 18). For the difference between <m>ā</m> and <m>ō</m> see the prepositions a and <m>o</m>. <m>A raua nei tama, ko Hau-maringi, ko Haumarotoroto</m> (M. xxxiv). Sometimes used elliptically. <m>Ka kai ratou i reira, pau ana ā nga hoa, katikati tonu a Tama</m> (T. 78). ‖ <m>tā</m> (iii).</p>"));
			arr.push( new WordItem( "Ā", "A.-iv ", "iv","<p>conj. denoting extension of space, or lapse of time; often very much prolonged in speech. <b>1</b>. <i>As far as</i>. <m>Ka rere mai a Te Arawa, ā waho i te moana</m> (T. 71). <m>Ka ra Hakomiti te ara, a Paritangi</m> (T. 78).</p> <p><b>2</b>. <i>Until</i>. <m>Takoto nei, a ao noa te ra</m> (T. 90).</p> <p><b>3</b>. <i>And, and then</i>; only connecting successive actions or events. <m>Hoe ana mai. a ka u ki Mokau</m> (T. 123). <m>Moe tonu, a ka ao te ra, ka hoe</m> (T. 196).</p>"));
			arr.push( new WordItem( "Ā", "A.-v ", "v","<p>colloquial = <m>aha</m>, pron. <i>What?</i> <m>He a tena, e Mati?</m></p>"));
			arr.push( new WordItem( "Ā", "A. ", "","<p>colloquial = <m>ae</m>, ad. <i>Yes</i>. <m>A hoki ra</m>, <i>just so</i>.</p>"));
			arr.push( new WordItem( "A", "A-i ", "i","<p>particle, used,—<b>1</b>. Before names of persons, the pronouns <m>wai</m> and <m>mea</m>, and names of canoes, months, etc.—(a) When they stand as subject in a sentence. <m>Kei te ngaki kumara a Te Kehu</m> (T. 85). <m>E tawharau ana mai a Te Arawa</m> (T. 81). (b) When they follow any of the prepositions <m>i, ki, hei, kei</m>. <m>Ka korero atu a Kupe ki a Turi</m> (T. 110). <m>Kua timata mai ano i mua atu i a Whakatauihu, i a Tawhaki, i a Tuhuruhuru</m> (T. 63). (c) In explanatory clauses. Kua tupu tana tamaiti, a Rata (T. 54).</p> <p><b>2</b>. Before personal pronouns, except <m>ahau</m> (though <m>au</m> follows this rule) — (a) When they follow any of the prepositions i, ki, <m>hei, kei</m>. <m>Ka mea ratou ki a koe ra</m> (T. 189). (b) When they are repeated by way of explanation, but not ordinarily when they stand as subject in a sentence. The use of the nominal prefix a before ia standing as subject of a verb is sometimes found.</p> <p><b>3</b>. Before names of places and local nouns (F.L. § 8) when they—(a) Stand as subject in a sentence. <m>Ka taunahatia e Naki a Motiti</m> (T. 75). <m>E puare katoa ana a roto</m> (T. 13). (b) Are repeated by way of explanation.</p> <p><b>4</b>. Occasionally before common nouns in explanatory clauses. <m>Rokohanga atu e takoto ana te kai nei, a te kukupa</m> (T. 146).</p> <p><b>5</b>. Sometimes, especially in animated narrative, merely euphonically. <m>Ma tona kaha a ia ano e taruturutu</m> (T. 159). <m>Na, me karanga a koe ki a au</m> (T. 168).</p>"));
			arr.push( new WordItem( "A", "A-ii ", "ii","<p>prep. <b>1</b>. <i>Of, belonging to</i>; used in speaking of transitive actions, including works accomplished or in progress, movable property, instruments, food, husband, wife, slaves, etc. (‖ <m>o</m>, prep., and F.L. § 22). <m>Ka mutu nga mahi a nga tama a Makeatutara</m> (T. 30). <m>Nga kupu poroporoaki a Hou</m> (T. 82). <m>Te umu a Kuiwai</m> (T. 83). <m>Ka haere mai nga matua o te wahine a Paoa</m> (T. 185).</p> <p><b>2</b>. <i>At, at the time of</i>; of future time. <m>A tahira te eke ai ki uta</m> (T. 142). <m>A whea ara ai te marama?</m> (T. 54).</p> <p><b>3</b>. <i>After the manner of</i>. <m>He mea mohio a ngakau tangata</m> (T. 84). <m>Rere a manu ki te hui matangohi</m> (M. 117). <m>Ka noho a pahi te rau ma whitu i reira</m> (T. 154).</p>"));
			arr.push( new WordItem( "A", "A-iii ", "iii","<p>ad. <b>1</b>. <i>Well, well then</i>. <m>A, tena, kei whea au tuaahu?</m> (T. 122). <m>A, hei konei whakarongo ake ai</m> (T. 10).</p> <p><b>2</b>. Sometimes simply to attract attention. <m>A, kāti te turituri</m> (T. 65).</p>"));
			arr.push( new WordItem( "A", "A-iv ", "iv","<p>in poetry = <m>ka</m>, particle. <m>A tuhi to toto, ka rapa i te rangi</m> (M. 83).</p>"));
			arr.push( new WordItem( "Ae", "Ae-i ", "i","<p>a. <i>Calm</i>. <m>Takoto noa tera te moana, he ae noa iho.</m></p>"));
			arr.push( new WordItem( "Ae", "Ae-ii ", "ii","<p><b>1</b>. ad. assenting to an affirmation or affirmative question. <i>Yes</i>. <m>“Ko koe tonu ranei?” Ka mea atu a Whakatau, “Ae, ko ahau”</m> (T. 62). <m>Ka mea atu te matua ki a ia, “Ae, e pai ana”</m> (T. 25).</p> <p><b>2</b>. In answer to a negative question it affirms the negative and must be rendered by <i>no</i>. <m>“Kahore i homai he kai mau?” “Ae.”</m> (<i>“Did not he give you any food?\" “No.”</i>) This use is almost obsolete.</p>    <p><b>3</b>. v.i. <i>Assent, agree</i>. <m>Ae ana mai ona whanaunga kia patua te ra</m> (T. 25).</p> <p><m>whakaae</m>, v.i. <i>Say yes, consent</i>. <m>Ka whakaae to raua whaea</m> (T. 46).</p>"));
			return arr;
		}
	}
}